version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\src\LetsEncrypt\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: oKDOIxq7y6H/WzuBM+AWsL06N620LYl9yJv0T+idpPaua3ZBl1wKRV1e1y3ajZsI
  on:
    branch: master
    appveyor_repo_tag: true
